# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='archive',
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
