# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170302_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_comments',
            field=models.IntegerField(default=0, verbose_name='# of comments'),
        ),
    ]
