# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20170424_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_likes',
        ),
    ]
