# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_number',
        ),
    ]
