# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-13 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
